- name: Configure the nginx document root folder in Ubuntu
  when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
  copy: src=default dest=/etc/nginx/sites-available/default backup=yes
